### ISSUE TITLE
It's not wait-free

### ISSUE THREAD

**Issue by MengRao** [dbittman/waitfree-mpsc-queue#9]
The reason is your comment in `mpscq_dequeue`, a thread can be suspended thus the consumer may not be able to make any progress even if the queue has data pushed by other producers.

Also I've made a MPMC queue template which is also almost wait-free(for the same reason) and zero-copy, and can also reside in shared-memory for IPC purpose: [WFMPMC](https://github.com/MengRao/WFMPMC)

**Comment by dbittman** [comment]
I think this depends on your definition of progress. The reason I wrote this is for use in kernel interrupt context in which nothing may block and must return in a bounded number of steps. Both operations fulfill this need. It's wait-free _if_ you allow for failure, which I do. In your example, just because there's work that _could_ be dequeued doesn't mean it _must_ be, because we may establish a different valid ordering between the threads' calls.

Cool! If I need those semantics (C++, MC, (mpscq is zero-copy)), I'll check it out. When I wrote this, I needed only single consumer for kernel-thread-processing reasons, so I didn't bother with the extra complexity. But I always meant to get around to writing one! Thanks for the link :)
